#Ifunny
type: IFUNNY
token: ""
tag: "deutsch"

spring:
  datasource:
    driver-class-name: "ru.yandex.clickhouse.ClickHouseDriver"
    url: "jdbc:clickhouse://docker01.dev.mdlp.crpt.tech:8123/default"
    username: ""
    password: ""
  redis:
    host: docker01.dev.mdlp.crpt.tech
    port: 6379
  kafka:
    producer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
      topic: "nanshakov3"