#Ifunny
type: NineGag
token: ""
tag: "deutsch"
endpoint: "http://docker01.dev.mdlp.crpt.tech"
accessKey: "minioadmin"
secretKey: "minioadmin"
bucket: "nanshakov"
port: 9999
logging:
  level:
    io.minio: debug
IFUNNY:
  download-url: "https://img.ifunny.co/images/"

spring:
  datasource:
    driver-class-name: "ru.yandex.clickhouse.ClickHouseDriver"
    url: "jdbc:clickhouse://docker01.dev.mdlp.crpt.tech:8123/default"
    username: ""
    password: ""
  redis:
    host: docker01.dev.mdlp.crpt.tech
    port: 6379
  kafka:
    topic: "nanshakov7"
    producer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
    consumer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
      group:
        id: 1
      auto-offset-reset: earliest
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
