#IFUNNY,NineGag
type: IFUNNY

IFUNNY:
  download-url: "https://img.ifunny.co/images/"
  tags: "deutsch"
  recursion:
    enable: true
    depth: 10000
    duplicates-count: 50 #сколько должно быть дубликатов подряд, что бы произошло переключение тега.

NineGag:
  download-url: "https://9gag.com/v1/search-posts?query="
  tags: "deutsch"
  recursion:
    enable: true
    depth: 10000
    duplicates-count: 50 #сколько должно быть дубликатов подряд, что бы произошло переключение тега.

spring:
  datasource:
    driver-class-name: "ru.yandex.clickhouse.ClickHouseDriver"
    url: "jdbc:clickhouse://docker01.dev.mdlp.crpt.tech:8123/default"
    username: ""
    password: ""
  redis:
    host: docker01.dev.mdlp.crpt.tech
    port: 6379
  kafka:
    topic: "nanshakov15"
    producer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
    consumer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
      group:
        id: 1
      auto-offset-reset: earliest

#metrics
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

endpoints:
  prometheus:
    enabled: true

#s3
s3.endpoint: "http://docker01.dev.mdlp.crpt.tech"
s3.accessKey: "minioadmin"
s3.secretKey: "minioadmin"
s3.bucket: "nanshakov"
s3.port: 9999

#loggers
logging:
  level:
    io.minio: debug

schema: "metaV2"