#Ifunny
type: IFUNNY
token: ""
tag: "deutsch"
endpoint: "docker01.dev.mdlp.crpt.tech:9999"
accessKey: "minioadmin"
secretKey: "minioadmin"
bucket: "nanshakov"
port: 9999
IFUNNY:
  download-url: "https://img.ifunny.co/images/"

spring:
  datasource:
    driver-class-name: "ru.yandex.clickhouse.ClickHouseDriver"
    url: "jdbc:clickhouse://docker01.dev.mdlp.crpt.tech:8123/default"
    username: ""
    password: ""
  redis:
    host: docker01.dev.mdlp.crpt.tech
    port: 6379
  kafka:
    topic: "nanshakov6"
    producer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
    consumer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
      group:
        id: 1
      auto-offset-reset: earliest