#Ifunny
type: IFUNNY
token: ""
tag: "deutsch"

spring:
  redis:
    host: docker01.dev.mdlp.crpt.tech
    port: 6379
  kafka:
    producer:
      bootstrap:
        servers: docker01.dev.mdlp.crpt.tech:9092
      topic: "nanshakov3"